conda-forge/pyside2-feedstock

recipe/meta.yaml

https://github.com/conda-forge/qt-feedstock/issues/62

Use conda gcc

---

.ci_support/linux_python2.7.yaml
.ci_support/linux_python3.6.yaml
.ci_support/linux_python3.7.yaml
.ci_support/osx_python2.7.yaml
.ci_support/osx_python3.6.yaml
.ci_support/osx_python3.7.yaml
.ci_support/win_c_compilervs2015cxx_compilervs2015python3.6vc14.yaml
.ci_support/win_c_compilervs2015cxx_compilervs2015python3.7vc14.yaml
recipe/meta.yaml

Remove clangdev from host

---

recipe/meta.yaml

No need for llvm

---

.ci_support/linux_python2.7.yaml
.ci_support/linux_python3.6.yaml
.ci_support/linux_python3.7.yaml
.ci_support/osx_python2.7.yaml
.ci_support/osx_python3.6.yaml
.ci_support/osx_python3.7.yaml
.ci_support/win_c_compilervs2015cxx_compilervs2015python3.6vc14.yaml
.ci_support/win_c_compilervs2015cxx_compilervs2015python3.7vc14.yaml
recipe/build.sh
recipe/meta.yaml

Check EGL fix

---

recipe/meta.yaml

Re-enable pyi on win

---

recipe/build.sh
recipe/meta.yaml

Cleanup xcb headers

---

.azure-pipelines/azure-pipelines-win.yml
.github/CODEOWNERS
.scripts/build_steps.sh
.scripts/run_osx_build.sh
README.md
recipe/meta.yaml

Just increase build number

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.azure-pipelines/azure-pipelines-win.yml
.ci_support/osx_arm64_python3.10.____cpython.yaml
.ci_support/osx_arm64_python3.8.____cpython.yaml
.ci_support/osx_arm64_python3.9.____cpython.yaml
.scripts/build_steps.sh
.scripts/create_conda_build_artifacts.bat
.scripts/create_conda_build_artifacts.sh
.scripts/run_osx_build.sh
LICENSE.txt
README.md
build-locally.py
conda-forge.yml
recipe/build.sh
recipe/meta.yaml
recipe/patches/cross_compile_pyi.patch

Checklist
This takes commits from #114 and #120 to get the builds to work on `osx-arm64`.

Changes to make #121 pass (osx-arm64 builds)

---

.azure-pipelines/azure-pipelines-linux.yml
.ci_support/linux_aarch64_python3.10.____cpython.yaml
.ci_support/linux_aarch64_python3.7.____cpython.yaml
.ci_support/linux_aarch64_python3.8.____cpython.yaml
.ci_support/linux_aarch64_python3.9.____cpython.yaml
.scripts/build_steps.sh
README.md
conda-forge.yml
recipe/build.sh
recipe/meta.yaml
recipe/yum_requirements.txt

Aarch with cross

---

.azure-pipelines/azure-pipelines-win.yml
.circleci/config.yml
.scripts/build_steps.sh
.scripts/run_osx_build.sh
README.md
recipe/build.sh
recipe/meta.yaml
recipe/patches/pysidebug-2127.patch

Update to 6.4.1

---

.ci_support/linux_64_python3.10.____cpython.yaml
.ci_support/linux_64_python3.8.____cpython.yaml
.ci_support/linux_64_python3.9.____cpython.yaml
.ci_support/linux_aarch64_python3.10.____cpython.yaml
.ci_support/linux_aarch64_python3.8.____cpython.yaml
.ci_support/linux_aarch64_python3.9.____cpython.yaml
.ci_support/osx_64_python3.10.____cpython.yaml
.ci_support/osx_64_python3.8.____cpython.yaml
.ci_support/osx_64_python3.9.____cpython.yaml
.ci_support/win_64_python3.10.____cpython.yaml
.ci_support/win_64_python3.8.____cpython.yaml
.ci_support/win_64_python3.9.____cpython.yaml
recipe/meta.yaml

6.x: Enable Qt3d

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.azure-pipelines/azure-pipelines-win.yml
.ci_support/linux_64_python3.11.____cpython.yaml
.ci_support/linux_aarch64_python3.11.____cpython.yaml
.ci_support/migrations/python311.yaml
.ci_support/osx_64_python3.11.____cpython.yaml
.ci_support/win_64_python3.11.____cpython.yaml
README.md

6.x: Rebuild for Python 3.11

---

recipe/meta.yaml
recipe/patches/support.patch

6.x: Drop QtNetworkAuth

---

recipe/build.sh
recipe/meta.yaml
recipe/patches/install_pyi.patch
recipe/patches/pymangle.patch
recipe/patches/support.patch

Update to 5.15.8

---

recipe/build.sh
recipe/meta.yaml
recipe/patches/gluint.patch

defaultFramebufferObject

---

recipe/bld.bat
recipe/build.sh
recipe/meta.yaml

Install dist-info

---

recipe/bld.bat
recipe/build.sh
recipe/meta.yaml
recipe/patches/tools.patch

6.x: Add uic/rcc

---

recipe/meta.yaml

Update to 6.5.1

---

.azure-pipelines/azure-pipelines-win.yml
.scripts/run_osx_build.sh
recipe/meta.yaml
recipe/patches/install_designer_plugin_path.patch

Update to 6.5.1.1

---

recipe/build.sh
recipe/meta.yaml

seems like they are looking for the vulkan headers too
Checklist

Pyside6 vulkan

---

recipe/meta.yaml

Build for 6.7.1

---

.scripts/build_steps.sh
.scripts/run_osx_build.sh
.scripts/run_win_build.bat
recipe/meta.yaml

Update to 6.7.2

---

recipe/meta.yaml
recipe/patches/1864c79.diff

BUG: Backport PyOS_InputHook bug fix for PYSIDE-2192

---

recipe/bld.bat
recipe/build.sh
recipe/meta.yaml

Try FORCE_LIMITED_API=OFF

---

.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_python3.10.____cpython.yaml
.ci_support/linux_64_python3.11.____cpython.yaml
.ci_support/linux_64_python3.12.____cpython.yaml
.ci_support/linux_64_python3.13.____cp313.yaml
.ci_support/linux_64_python3.9.____cpython.yaml
.ci_support/linux_aarch64_python3.10.____cpython.yaml
.ci_support/linux_aarch64_python3.11.____cpython.yaml
.ci_support/linux_aarch64_python3.12.____cpython.yaml
.ci_support/linux_aarch64_python3.13.____cp313.yaml
.ci_support/linux_aarch64_python3.9.____cpython.yaml
.ci_support/osx_64_python3.10.____cpython.yaml
.ci_support/osx_64_python3.11.____cpython.yaml
.ci_support/osx_64_python3.12.____cpython.yaml
.ci_support/osx_64_python3.13.____cp313.yaml
.ci_support/osx_64_python3.9.____cpython.yaml
.ci_support/osx_arm64_python3.10.____cpython.yaml
.ci_support/osx_arm64_python3.11.____cpython.yaml
.ci_support/osx_arm64_python3.12.____cpython.yaml
.ci_support/osx_arm64_python3.13.____cp313.yaml
.ci_support/osx_arm64_python3.9.____cpython.yaml
.ci_support/win_64_python3.10.____cpython.yaml
.ci_support/win_64_python3.11.____cpython.yaml
.ci_support/win_64_python3.12.____cpython.yaml
.ci_support/win_64_python3.13.____cp313.yaml
.ci_support/win_64_python3.9.____cpython.yaml
azure-pipelines.yml
recipe/build.sh
recipe/meta.yaml

Update to 6.8.0

---

.gitignore
recipe/meta.yaml

Update to 6.8.2

---

recipe/meta.yaml

This should help with https://github.com/conda-forge/vtk-feedstock/pull/375#issuecomment-2760685256 .
Checklist

[draft] Update to 6.8.3

---

.ci_support/win_64_python3.10.____cpython.yaml
.ci_support/win_64_python3.11.____cpython.yaml
.ci_support/win_64_python3.12.____cpython.yaml
.ci_support/win_64_python3.13.____cp313.yaml
.ci_support/win_64_python3.9.____cpython.yaml
.gitignore
.scripts/run_docker_build.sh
build-locally.py
recipe/conda_build_config.yaml
recipe/meta.yaml

Update to 6.9.0

---

recipe/meta.yaml
recipe/patches/wayland_expose_1.patch
recipe/patches/wayland_expose_2.patch

Backport patches for improved wayland support
